-- INTERVAL type
-- YEAR TO MONTH, DAY TO SECOND

-- INTERVAL literal
ALTER SESSION SET nls_date_format = 'yyyy-mm-dd hh24:mi:ss';

SELECT SYSDATE, SYSDATE + INTERVAL '3-2' YEAR TO MONTH AS new_day FROM dual;
SELECT SYSDATE, SYSDATE + INTERVAL '3-12' YEAR TO MONTH AS new_day FROM dual;  -- ERROR
SELECT SYSDATE, SYSDATE + INTERVAL '3-11' YEAR TO MONTH AS new_day FROM dual;

-- 년도만 지정
SELECT SYSDATE, SYSDATE + INTERVAL '3' YEAR AS new_day FROM dual;
SELECT SYSDATE, SYSDATE + INTERVAL '3-0' YEAR TO MONTH AS new_day FROM dual;

-- 월만 지정
SELECT SYSDATE, SYSDATE + INTERVAL '3' MONTH AS new_day FROM dual;
SELECT SYSDATE, SYSDATE + INTERVAL '0-3' YEAR TO MONTH AS new_day FROM dual;
SELECT SYSDATE, SYSDATE + INTERVAL '13' MONTH AS new_day FROM dual;

-- 3자리 이상인 년
SELECT SYSDATE, SYSDATE + INTERVAL '-100' YEAR(3) AS new_day FROM dual;
SELECT SYSDATE, SYSDATE - INTERVAL '100' YEAR(3) AS new_day FROM dual;


-- DAY TO SECOND
SELECT SYSDATE, SYSDATE + INTERVAL '3 1:23:5' DAY TO SECOND AS new_time FROM dual;
SELECT SYSDATE, SYSDATE + INTERVAL '7' DAY AS new_time FROM dual;
SELECT SYSDATE, SYSDATE + INTERVAL '7' HOUR AS new_time FROM dual;
SELECT SYSDATE, SYSDATE + INTERVAL '10:5' MINUTE TO SECOND AS new_time FROM dual;
SELECT SYSDATE, SYSDATE + INTERVAL '10:5' HOUR TO MINUTE AS new_time FROM dual;
SELECT SYSDATE, SYSDATE + INTERVAL '10 5' DAY TO HOUR AS new_time FROM dual;
SELECT SYSDATE, SYSDATE + INTERVAL '100' DAY(3) AS new_time FROM dual;
SELECT SYSDATE, SYSDATE + INTERVAL '10:60' MINUTE TO SECOND AS new_time FROM dual;  -- ERROR
SELECT SYSDATE, SYSDATE + INTERVAL '1 120' DAY TO HOUR AS new_time FROM dual;

-- NUMTOYMINTERVAL, NUMTODSINTERVAL 함수
SELECT SYSDATE, SYSDATE + NUMTOYMINTERVAL(100, 'year') FROM dual;
SELECT SYSDATE, SYSDATE + NUMTOYMINTERVAL(100, 'month') FROM dual;
SELECT SYSDATE, SYSDATE + NUMTOYMINTERVAL(3, 'YEAR') + NUMTOYMINTERVAL(100, 'month') FROM dual;


CREATE TABLE product (
  id NUMBER,
  name VARCHAR2(30),
  pur_date DATE,
  warranty INTERVAL DAY(3) TO SECOND
);

INSERT INTO product VALUES (1, 'TV', SYSDATE, NUMTODSINTERVAL(100, 'day'));
SELECT * FROM product;