CREATE TABLE test (
    c1 NUMBER PRIMARY KEY,
    c2 VARCHAR2(10)
);

ALTER TABLE test
ADD CONSTRAINT test_uk UNIONE (c2);

INSERT INTO test VALUES (1, 'H1');
INSERT INTO test VALUES (2, NULL);
INSERT INTO test VALUES (3, '안녕');
INSERT INTO test VALUES (4, NULL);
INSERT INTO test VALUES (5, NULL);
INSERT INTO test VALUES (6, 'hi');

SELECT * FROM test;